declare module '@kongponents/kinput'
declare module '@kongponents/kcard'
declare module '@kongponents/kalert'
declare module '@kongponents/klabel'
declare module '@kongponents/kbutton'
declare module '@kongponents/kicon'
declare module '@kongponents/kcheckbox'
declare module '@kongponents/kooltip'
