name: Cleanup PR preview packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * 6,0'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup PR Previews
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

