name: Lint Commit Messages

on:
  pull_request:

jobs:
  commitlint:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'flycode-app[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.4.1
