name: Publish

on:
  push:
    branches: [main]

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    # Must pass in secrets here so that the calling workflow can pass in the NPM_TOKEN needed to install private packages.
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}
      VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL }}
  publish:
    needs: run-tests
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Create .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_PUBLIC_PUBLISH}" > .npmrc

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          # Since branch protections are on (pushing commits) you need to use a bot PAT
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}

      - name: Trigger a build for packages.konghq.tech
        if: ${{ success() }}
        run: |
          curl -X POST \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              -H  'Content-Type: application/json' \
              -H 'Authorization: token ${{ secrets.KONGPONENTS_BOT_PAT }}' \
              --data '{"event_type": "webhook"}' https://api.github.com/repos/Kong/package-publisher/dispatches
