name: Publish

on:
  push:
    branches: [main]

jobs:
  run-tests:
    name: Tests
    uses: Kong/kong-auth-elements/.github/workflows/test.yml@main
  publish:
    needs: run-tests
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Copy .npmrc.ci
        run: cp .npmrc.ci .npmrc

      - name: Install dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
