name: Tests

on:
  pull_request:
    branches: [main]
  # Allow workflow to be called by another workflow
  workflow_call:
    # Must define secrets here so that the calling workflow can pass in the NPM_TOKEN needed to install private packages.
    secrets:
      NPM_TOKEN:
        description: 'The NPM_TOKEN passed from the caller workflow as it is not available within workflow_call.'
        required: true
      VITE_AUTH_URL:
        description: 'The base URL of the KAuth backend, e.g. https://konnect.konghq.tech'
        required: true
  # Allow workflow to be called manually
  workflow_dispatch:
    inputs:
      VITE_AUTH_URL:
        description: 'The base URL of the KAuth backend, e.g. https://konnect.konghq.tech'
        type: string
        default: https://konnect.konghq.tech
        required: false

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:

      - name: Remove preview consumption comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_preview_consumption
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          command: yarn test
        env:
          VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL || inputs.VITE_AUTH_URL }}

      - name: Upload Cypress screenshots (on failure)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/

      - name: Build
        if: github.event_name == 'pull_request'
        run: yarn build

      - name: Upload Cypress videos (always)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/

      - name: Publish Previews
        if: github.event_name == 'pull_request'
        run: |
          git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
          git config user.name "Kong UI Bot"

          preid="pr.${{ github.event.pull_request.number }}.$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
          tag="pr-${{ github.event.pull_request.number }}"
          echo "preid=${preid}"

          git checkout ${{ github.head_ref }}

          yarn version --prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --no-git-tag-version  --yes --amend

          npm_instructions=""
          rm .npmrc
          pkg=$(npm publish  --no-git-checks --access restricted --report-summary --tag "${tag}" | grep "+ "| sed 's/+ //')

          if [[ -z "${pkg}" ]]; then
            echo "Error publishing package"
            exit -1
          fi

          npm_instructions="@$(echo ${pkg}|cut -d'@' -f2)@${tag}"

          echo "npm_instructions<<EOF" >> $GITHUB_ENV
          echo -e "$npm_instructions" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Provide preview link info
        if: ${{ env.npm_instructions != '' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_preview_consumption
          message: |
             ## ***Preview*** package from this PR in consuming application
             In consuming application project install preview version of kong-auth-elements generated by this PR:
             ```
             ${{env.npm_instructions}}
             ```
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

