name: Tests

on:
  pull_request:
    branches: [main]
  # Allow workflow to be called by another workflow
  workflow_call:
  # Allow workflow to be called manually
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn test

      - name: Upload Cypress screenshots (on failure)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/

      - name: Upload Cypress videos (always)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/
