name: Tests

on:
  pull_request:
    branches: [main]
  # Allow workflow to be called by another workflow
  workflow_call:
  # Allow workflow to be called manually
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: nvm
        name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install

      # Only to make sure this doesn't fail
      - name: Generate API Client
        run: yarn generate:api-client

      - name: Lint
        run: yarn lint

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn test
          browser: chrome

      - name: Upload Cypress screenshots (on failure)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/

      - name: Upload Cypress videos (always)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/
