name: Test

on:
  pull_request:
    branches: [main]
  # Allow workflow to be called by another workflow
  workflow_call:
  # Allow workflow to be called manually
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: nvm
        name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install

        # Only to make sure this doesn't fail
      - name: Generate API Client
        run: yarn generate:api-client

      - name: Lint
        run: yarn lint

      # Run unit tests
      - name: Run unit tests
        run: yarn run test:unit
